name: bookmyapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
  
dependency_overrides:
  firebase_core_platform_interface: 4.5.1
# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.4.9
  splashscreen: ^1.3.5
  firebase_auth: ^3.10.0
  firebase_core: ^1.24.0
  flutter_icons: ^1.1.0
  geolocator: ^9.0.2
  url_launcher: ^6.1.6
  firebase_analytics: ^9.3.8
  cloud_functions: ^3.3.9
  geocoding: ^2.0.5
  http: ^0.13.5
  google_maps_flutter: ^2.2.1
  dio: ^4.0.6
  flutter_polyline_points: ^1.0.0
  maps_launcher: ^2.0.1
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  flutter_secure_storage: ^6.0.0
  google_sign_in: ^5.4.2
  email_validator: ^2.1.17
  auth_service: ^0.0.2
  scroll_snap_list: ^0.9.1
  carousel_slider: ^4.1.1
  intl: ^0.17.0
  flutter_tabler_icons: ^1.1.1
  connectivity: ^3.0.6
  image_picker: ^0.8.6
  permission_handler: ^10.2.0
  date_format: ^2.0.7
  getwidget: ^3.0.1
  video_player: ^2.4.7
  flutter_rating_bar: ^4.0.1
  location: ^4.4.0
  app_settings: ^4.1.8
  firebase_storage: ^10.2.13
  equatable: ^2.0.5
  material_dialogs: ^1.1.3
  google_fonts: ^3.0.1
  connection_status_bar: ^1.1.6
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.6.2
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  animated_icon: ^0.0.4
  checkmark: ^0.0.2+1
  fluttertoast: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
flutter_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
        - assets/images/bookmyshow.png
        - assets/images/my.jpeg
        - assets/images/splashLogo.png
        - assets/images/bookmylogo.png
        - assets/images/popcorn.png
        - assets/images/coming.png
        - assets/images/avatar.png
        - assets/images/bookandsmile.jpg
        - assets/images/cinema.webp
        - assets/images/rewards.webp
        - assets/images/theater.png
        - assets/images/bookone.jpg
        - assets/images/background.png
        - assets/images/popcorn-nouns-dao.gif
        - assets/images/greentick.gif
        - assets/images/movieloading.gif
        - assets/images/welcomeimage.webp
        - assets/images/noInternet.webp
        - assets/images/imageerror.jpg
        - assets/images/errorr.webp
        - assets/images/firstOffer.jpg
        - assets/images/secondOffer.jpg
        - assets/images/thirdOffer.jpg
        - assets/images/greensuccess.gif
        - assets/images/cameera.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  